require("core.notifications")
require("core.dbus")
require("core.volume")
require("core.layouts")
require("core.screens")
require("core.rules")
require("core.signals")
require("core.bindings")
-- require("core.battery")
